name: Allure Report CI

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  autotests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build and Run Tests
        # Примечание: на самом GitHub приложение jar не запущено,
        # тесты сгенерируют нужные JSON файлы для структуры отчета
        run: mvn test || true

      - name: Get Allure history
        # Подтягиваем историю прошлых запусков для красивых графиков трендов
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-deploy-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
